export const GET_ALL_VIDEOS = "GET_ALL_VIDEOS";
export const CHANGE_STATION = "CHANGE_STATION";
export const TOGGLE_PLAYING = "TOGGLE_PLAYING";
export const INCREMENT_ADS_COUNTER = "INCREMENT_ADS_COUNTER";